/* eslint-disable react/jsx-no-undef */
import './globals.css';
import type { Metadata } from 'next';
import { Rubik } from 'next/font/google';
import Providers from '@/lib/Providers';
import { ConfigProvider } from 'antd';

const rubik = Rubik({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800'],
});

export const metadata: Metadata = {
  title: 'MSP Tutoring Service',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={rubik.className}>
        <ConfigProvider
          theme={{
            token: {
              fontFamily: 'rubik',
              fontSize: 16, // Alias Token
            },
          }}
        >
          <Providers>{children}</Providers>
        </ConfigProvider>
      </body>
    </html>
  );
}
